defaults:
  - default

strategy: ddp # ddp_find_unused_parameters_true # may slower the run : https://lightning.ai/releases/2.0.0/

accelerator: gpu
devices: 4 # num_gpu
num_nodes: 2
sync_batchnorm: True
