defaults:
  - default

strategy: ddp

accelerator: gpu
devices: 4 # num_gpu
num_nodes: 2
sync_batchnorm: True
#num_worker: 8 doesn't exist

#SBATCH --account=ofp@v100
#SBATCH --job-name=train_diff_fusion_cd # nom du job 

##SBATCH -C v100-32g
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=4          # avec 2 tache par noeud (= nombre de GPU ici)
#SBATCH --gres=gpu:4               # nbr of GPU per node
#SBATCH --cpus-per-task=8         # nbr of cores per task
#SBATCH --hint=nomultithread        # physical core
