_target_: src.models.magic_pen.modules.BitemporalTransformerBlocks
dim: 768
num_heads: 12
mlp_ratio: 4.0
qkv_bias: True
use_rel_pos: False
rel_pos_zero_init: True
window_size: 0
input_size: null
tuner_strategy: null
