defaults:
  - default
  - _self_

_target_: src.models.magic_pen.bisam_attnconc.BiSamAttn
embedding_dim: 256
num_heads: 8
num_patches: 4096
n_modalities: 2

mask_decoder:
  transformer_dim: 512
  iou_head_hidden_dim: 256 # need to modify it ?
  transformer:
    embedding_dim: 512 
prompt_encoder:
  embed_dim: 512

