defaults:
  - image_encoder: ??
  - prompt_encoder: sam_prompt_encoder
  - mask_decoder: sam_mask_decoder
  - _self_

_target_: src.models.magic_pen.bisam_concat.BiSamConcat

mask_decoder:
  transformer_dim: 512
  iou_head_hidden_dim: 256 # need to modify it ?
  transformer:
    embedding_dim: 512 
prompt_encoder:
  embed_dim: 512

