defaults:
  - image_encoder: ??
  - prompt_encoder: sam_prompt_encoder
  - mask_decoder: sam_mask_decoder
  - _self_

_target_: src.models.commons.model.BiSam

pixel_mean:
  - 123.675
  - 116.28
  - 103.53
pixel_std:
  - 58.395
  - 57.12
  - 57.375