defaults:
  - bitemporal_embedding_fusion: default
  - image_encoder: default
  - prompt_encoder: default
  - prompt_to_image: default
  - tuner_strategy: adapter
  - _self_


iou_head:
  _target_: src.models.lestylonet.heads.IouPredHead
  transformer_dim: 256
  iou_head_hidden_dim:  256
  num_mask_tokens: 3
  iou_head_depth: 3

mask_head:
  _target_: src.models.lestylonet.heads.MaskHead
  strategy: # not very useful
    _target_: src.models.lestylonet.heads.SAMMaskHead
    num_mask_tokens: 3
    transformer_dim: 256

params:
  sam_ckpt_path: ?? # defined globally in sam_type
  use_weights:
    - image_encoder

