_target_: src.models.segment_anything.modeling.image_encoder_dev.ImageEncoderViT

depth: 32
embed_dim: 1280
img_size: 1024
mlp_ratio: 4
norm_layer: null
num_heads: 16
patch_size: 16
qkv_bias: True
use_rel_pos: True
global_attn_indexes:
  - 7
  - 15
  - 23
  - 31
window_size: 14
out_chans: 256