_target_: src.models.segment_anything.modeling.image_encoder_dev.ImageEncoderViT

depth: 12
embed_dim: 768
img_size: 1024
mlp_ratio: 4
norm_layer: null
num_heads: 12
patch_size: 16
qkv_bias: True
use_rel_pos: True
global_attn_indexes:
  - 2
  - 5
  - 8
  - 11
window_size: 14
out_chans: 256