_target_: src.models.commons.losses.Losses
losses: {
  FOCAL : {
    params: {
      gamma: 2, # exponent term
      alpha: 0.25, # weighting factor in range (0,1) to balance positive vs negative examples 
      reduction: "mean" # mean or sum or None
    },
    weight: 1.0
    },
  DICE : {
    params: {},
    weight: 1.0
  }
}