defaults:
  - network: bisam_concat
  - optimizer: adam
  - scheduler: cosinewarm
  - _self_

instance:
  _target_: src.models.magic_pen.task.MagicPenModule
  network: ${model.network} # try to merge instead with @_here_
  task_name: ??
  optimizer: ${model.optimizer}
  scheduler: ${model.scheduler}
