defaults:
  - network: bisam
  - _self_

instance:
  _target_: src.models.segment_any_change.task.CDModule
  params:
    num_worker: ??
    n_job_by_node: ??
    model_type: ??
    batch_size: ??

  model: 
    _target_: src.models.segment_any_change.query_prompt.SegAnyPrompt
    matching_engine:
      _target_: src.models.segment_any_change.matching.BitemporalMatching
      th_change_proposals: ??
      col_nms_threshold: ?? 
      sam_ckpt_path: ??
      network: ${model.network}