
defaults:
  - data: second
  - model: seganychange
  - callbacks: default
  - logger: tensorboard
  - trainer: default
  - paths: default
  # - extras: default
  - hydra: default
  - hparams_search: null # config for hyperparameter optimization
  - optional local: default # optional local config for machine/user specific settings
  - debug: null # debugging config (enable through command line, e.g. `python train.py debug=default)
  - exp: null
  - _self_
  
task_name: "eval"
tags: ["eval"]
# data_dir: ${paths.data_dir}/${dataset.name}/
compile: True # compile model for faster training with pytorch 2.0
seed: 32 # seed for random number generators in pytorch, numpy and python.random
# experiment_name: ${dataset.name}_${model.name}

sam_ckpt_path: null