# order of defaults determines the order in which configs override each other
defaults:
  - data: ??
  - model: ??
  - sam_type: ??
  - experiment: ??
  - callbacks: default
  - logger: tensorboard 
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default
  - hparams_search: null # config for hyperparameter optimization
  - optional local: default # optional local config for machine/user specific settings
  - debug: null # debugging config (enable through command line, e.g. `python train.py debug=default)
  - _self_

task_name: "overfit_sample"

tags: ["dev"]

# set False to skip model training
train: True

# evaluate on test set, using best model weights achieved during training
# lightning chooses best weights based on the metric specified in checkpoint callback
test: True

ckpt_path: null
seed: 66
