# @package _global_

defaults:
  - override /data: ??
  - override /model: seganyprompt
  - _self_
data:
  params:
    prompt_type: "sample"
    n_prompt: 1
    n_shape: 3
    ds_sample: 4
model:
  instance:
    model: 
      n_points_grid: 30