# @package _global_

defaults:
  - override /data: ??

trainer:
  max_epochs: 1
  accelerator: gpu # debuggers don't like gpus
  precision: 16-mixed # fp16 won't work on cpu
data:
  params:
    ds_sample: 10
    num_worker: 0