# @package _global_

defaults:
  - override /data: ??

trainer:
  max_epochs: 3
  accelerator: cpu # debuggers don't like gpus
  precision: 32 #16-mixed # fp16 won't work on cpu
data:
  params:
    ds_sample: 4
    num_worker: 0