# https://pytorch.org/docs/stable/generated/torch.optim.lr_scheduler.CosineAnnealingWarmRestarts.html#torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
_target_: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
_partial_: true # partial https://hydra.cc/docs/advanced/instantiate_objects/overview/
T_0: 32
T_mult: 1 
eta_min: 0.000001